### PR TITLE
Add Entry for Android TV launchers

### PR DESCRIPTION
**Pull request by hathlife**
Add manifests for ATV launcher entry and banner following ATV design guides by Google.

### CODE REVIEW

**Comment by txyyh** [comment]
Wait! We need test!

**Comment by txyyh** [comment]
@hathlife please sent the screenshots

**Comment by asuka-mio** [comment]
We will compress these resources to reduce size later since they are such a little big

**Comment by txyyh** [comment]
And please note: we won't use panda icon
We will notify you when we design new icon down

**Comment by hathlife** [comment]
> @hathlife please send the screenshots here

image




> And please note: we won't use panda icon We will notify you when we design new icon down
> 
> And, Please, **DO NOT** separate the word "EhViewer"

An upscaled version of official favicon would be a good idea
↓
image

**Comment by txyyh** [comment]
@hathlife icon updated

**Pull request merged**
